### ISSUE TITLE
"std::bad_alloc" when testing on my data

### ISSUE THREAD

**Issue by DarwinAwardWinner** [thomasp85/tweenr#7] opened 2016-08-29 21:05 UTC
Steps to reproduce:

```R
library(tweenr)
x <- readRDS(gzcon(url("https://www.dropbox.com/s/rc6l97av6dgzeyp/tweenr-bug.RDS?dl=1")))
tween_elements(x, "PODFrame", "AnimalID", "ease", nframes=500)
```

Error message:

```
> tween_elements(x, "PODFrame", "AnimalID", "ease", nframes=500)
Error: std::bad_alloc
> traceback()
7: stop(list(message = "std::bad_alloc", call = NULL, cppstack = NULL))
6: .Call("tweenr_numeric_element_interpolator", PACKAGE = "tweenr", 
       data, group, frame, ease)
5: numeric_element_interpolator(data, group, frame, ease)
4: interpolate_numeric_element(d, group, frame, ease)
3: FUN(X[[i]], ...)
2: lapply(seq_along(data), function(i) {
       d <- data[[i]]
       switch(colClasses[i], numeric = interpolate_numeric_element(d, 
           group, frame, ease), factor = interpolate_factor_element(d, 
           group, frame, ease), character = interpolate_character_element(d, 
           group, frame, ease), colour = interpolate_colour_element(d, 
           group, frame, ease), date = interpolate_date_element(d, 
           group, frame, ease), datetime = interpolate_datetime_element(d, 
           group, frame, ease), constant = interpolate_constant_element(d, 
           group, frame, ease))
   })
1: tween_elements(x, "PODFrame", "AnimalID", "ease", nframes = 500)
```

**Comment by thomasp85** [comment] 2016-08-30 07:52
duplicate of #4

**Closed by thomasp85** 2016-08-30 07:52 UTC
